### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by binwiederhier** [yossi-abramov/simple-lightbox.github.io#1]
Howdy! Thank you very much for this wonderful example of a Lightbox. Unfortunately there is no license attached to this repo, which means technically it's not usable without violating your copyright. Could you add a license to it?

**Comment by umer936** [comment]
@yossi-abramov Wanted to bump this. I would like to use it in a project. 

https://choosealicense.com/licenses/ 

I typically pick the MIT license for my projects. Sometimes the Unlicense if I don't care where it ends up.

**Comment by yossi-abramov** [comment]
Hey @umer936 @binwiederhier 
Added a license. Feel free to share/modify/use 👍

**Comment by umer936** [comment]
Awesome, thanks! 😃 
This issue can be closed
